-- NeighbourLend - MySQL Items Insert Script
-- Inserts 50 realistic Indian household rental items.
-- Note: Assumes that users with ID 1 and 2 exist in the 'users' table.

INSERT INTO items (id, name, description, price, category, image_url, available, user_id, weekly_rate, security_deposit, city, state, owner_name) VALUES
-- Tools (1-5)
(1, 'Stanley Claw Hammer (16 oz)', 'Genuine Stanley claw hammer, heavy duty steel. Perfect for home DIY, hanging frames, or minor repairs. Please return after clean use.', 30.0, 'Tools', '/images/items/hammer.jpg', 1, 1, 150.0, 200.0, 'Mumbai', 'Maharashtra', 'Amit Sharma'),
(2, 'Bosch Cordless Electric Drill (12V)', 'Powerful Bosch cordless drill with 2 rechargeable batteries and screwdriver bits. Ideal for wood, metal, and masonry drilling.', 200.0, 'Tools', '/images/items/drill.jpg', 1, 1, 1000.0, 1500.0, 'Bengaluru', 'Karnataka', 'Rohan Verma'),
(3, 'Taparia Multi-bit Screwdriver Set', 'High-quality Taparia screwdriver kit with extension rods and 31 various bit types (Star, Flat, Torx). Magnetic tips make it easy to use.', 40.0, 'Tools', '/images/items/screwdriver.jpg', 1, 2, 200.0, 300.0, 'Delhi', 'Delhi', 'Vikram Malhotra'),
(4, 'Aluminium Foldable Ladder (6 Steps)', 'Lightweight, highly stable 6-step aluminium ladder. Reach ceiling heights easily for cleaning, painting, or light bulb changes.', 100.0, 'Tools', '/images/items/ladder.jpg', 1, 2, 500.0, 1000.0, 'Chennai', 'Tamil Nadu', 'Suresh Pillai'),
(5, 'Karcher K2 Compact Pressure Washer', 'High-pressure washer perfect for cleaning cars, bikes, balconies, and driveways. Comes with spray gun and 4m high-pressure hose.', 250.0, 'Tools', '/images/items/pressure_washer.jpg', 1, 1, 1200.0, 2000.0, 'Pune', 'Maharashtra', 'Deepak Joshi'),

-- Electronics (6-10)
(6, 'Epson EB-E01 XGA Projector', 'High brightness 3LCD projector with HDMI and VGA ports. Perfect for movie nights, gaming sessions, or corporate presentations.', 600.0, 'Electronics', '/images/items/projector.jpg', 1, 1, 3000.0, 5000.0, 'Kolkata', 'West Bengal', 'Kunal Sen'),
(7, 'Canon EOS 1500D DSLR Camera', 'Easy-to-use Canon DSLR with 18-55mm lens. Perfect for travel photography, vlogging, or family events. Comes with 16GB memory card, battery, and charger.', 800.0, 'Electronics', '/images/items/dslr_camera.jpg', 1, 1, 4000.0, 8000.0, 'Kochi', 'Kerala', 'Ananya Iyer'),
(8, 'JBL Charge 5 Bluetooth Speaker', 'IP67 waterproof Bluetooth speaker with rich JBL Pro Sound and built-in powerbank. Up to 20 hours of playtime. Great for small gatherings.', 150.0, 'Electronics', '/images/items/bluetooth_speaker.jpg', 1, 2, 800.0, 1500.0, 'Mysuru', 'Karnataka', 'Rahul Roy'),
(9, 'Dell 24-inch Full HD IPS Monitor', 'Dell thin-bezel IPS monitor with HDMI and VGA inputs. Perfect for setting up a temporary work-from-home space or dual-screen coding.', 200.0, 'Electronics', '/images/items/monitor.jpg', 1, 2, 1000.0, 3000.0, 'Hyderabad', 'Telangana', 'Siddharth Rao'),
(10, 'Mi Boost Pro 30000mAh Power Bank', 'High capacity power bank with 18W fast charging and triple output ports. Keeps your devices powered during long travel or power cuts.', 50.0, 'Electronics', '/images/items/power_bank.jpg', 1, 1, 250.0, 500.0, 'Ahmedabad', 'Gujarat', 'Pranav Mehta'),

-- Kitchen (11-15)
(11, 'Prestige Iris 750W Mixer Grinder', 'Powerful 750-watt motor mixer grinder with 3 stainless steel jars and 1 juicer jar. Excellent for grinding idli/dosa batter or spices.', 80.0, 'Kitchen', '/images/items/mixer_grinder.jpg', 1, 1, 400.0, 800.0, 'Madurai', 'Tamil Nadu', 'Meera Nair'),
(12, 'Philips Viva Induction Cooktop', 'Sleek glass cooktop with preset Indian cooking menus (roti, idli, milk, gravy). Electromagnetic induction makes cooking fast and safe.', 100.0, 'Kitchen', '/images/items/induction_stove.jpg', 1, 1, 500.0, 1200.0, 'Coimbatore', 'Tamil Nadu', 'Sandhya Nair'),
(13, 'Havells Grande 4L Air Fryer', 'Healthy cooking with up to 85% less oil. 4-liter capacity, digital touch panel, and auto-off timer. Ideal for making samosas and fries.', 180.0, 'Kitchen', '/images/items/air_fryer.jpg', 1, 2, 900.0, 2000.0, 'Noida', 'Uttar Pradesh', 'Neelam Gupta'),
(14, 'Panasonic Automatic Electric Rice Cooker', 'Cooks up to 1 kg of raw rice perfectly. Keep-warm function ensures your rice stays hot for hours. Clean, lightweight, and user-friendly.', 70.0, 'Kitchen', '/images/items/rice_cooker.jpg', 1, 2, 350.0, 800.0, 'Chennai', 'Tamil Nadu', 'Rajesh Kannan'),
(15, 'Samsung 23L Solo Microwave Oven', 'Solo microwave for heating, defrosting, and simple cooking. Features ceramic enamel cavity which is easy to clean. Includes glass turntable.', 150.0, 'Kitchen', '/images/items/microwave.jpg', 1, 1, 750.0, 2500.0, 'Pune', 'Maharashtra', 'Divya Deshmukh'),

-- Furniture (16-20)
(16, 'Supreme Plastic Armchairs (Set of 4)', 'Sturdy, stackable plastic chairs with armrests. Great for hosting extra guests at home for family get-togethers or prayer sessions.', 40.0, 'Furniture', '/images/items/plastic_chairs.jpg', 1, 1, 200.0, 500.0, 'Kochi', 'Kerala', 'Ramesh Kumar'),
(17, 'Nilkamal Foldable Plastic Table', 'Convenient rectangular foldable table. Lightweight and easy to set up inside or on balconies for study, dining, or outdoor snacks.', 60.0, 'Furniture', '/images/items/foldable_table.jpg', 1, 1, 300.0, 800.0, 'Mysuru', 'Karnataka', 'Karthik Raja'),
(18, 'Decornation Solid Wood Study Table', 'Wooden writing desk with drawer. Spacious tabletop to keep a laptop, notebook, and lamp. Sleek design, perfect for short-term study needs.', 120.0, 'Furniture', '/images/items/study_table.jpg', 1, 2, 600.0, 2000.0, 'Kolkata', 'West Bengal', 'Arjun Das'),
(19, 'Green Soul Ergonomic Office Chair', 'High-back mesh chair with lumbar support, adjustable height, and comfortable armrests. Perfect for long hours of working or studying.', 150.0, 'Furniture', '/images/items/office_chair.jpg', 1, 2, 850.0, 2500.0, 'Bengaluru', 'Karnataka', 'Pooja Hegde'),
(20, 'DeckUp 3-Tier Wooden Bookshelf', 'Compact 3-tier wooden shelf to organize books, files, or decorative items. Fits easily into corners. Cleaned and ready to use.', 80.0, 'Furniture', '/images/items/bookshelf.jpg', 1, 1, 400.0, 1200.0, 'Delhi', 'Delhi', 'Shalini Sharma'),

-- Vehicles (21-25)
(21, 'Hero Sprint Next 24T Gear Cycle', 'Dual suspension 18-speed mountain bicycle. Ideal for daily commuting or exploring city trails. Comes with front/rear mudguards.', 100.0, 'Vehicles', '/images/items/bicycle.jpg', 1, 1, 550.0, 1500.0, 'Chennai', 'Tamil Nadu', 'Vijay Sethupathi'),
(22, 'Ather 450X Gen 3 Electric Scooter', 'Ather electric scooter in excellent condition. Eco and Sport modes, range up to 85 km on full charge. Charger included. DL copy required.', 400.0, 'Vehicles', '/images/items/electric_scooter.jpg', 1, 1, 2200.0, 5000.0, 'Bengaluru', 'Karnataka', 'Nikhil Gowda'),
(23, 'Montra Madrock 29T Mountain Bike', 'High performance mountain bike with 21-speed Shimano gears and front zoom suspension. Great for weekend trail rides. Helmet provided.', 150.0, 'Vehicles', '/images/items/mountain_bike.jpg', 1, 2, 800.0, 2000.0, 'Kochi', 'Kerala', 'Ajith Kumar'),
(24, 'Decathlon Btwin Tilt 120 Folding Bike', '6-speed folding bicycle. Folds in 30 seconds, fits easily into a car trunk. Perfect for park rides or city exploration.', 120.0, 'Vehicles', '/images/items/folding_bike.jpg', 1, 2, 650.0, 1800.0, 'Mumbai', 'Maharashtra', 'Varun Dhawan'),
(25, 'Firefox Target 21-Speed Hybrid Bike', 'Lightweight alloy frame hybrid bicycle. Smooth rolling tires for pavement and road. Well maintained, brakes and gears are tuned.', 140.0, 'Vehicles', '/images/items/hybrid_bike.jpg', 1, 1, 750.0, 2000.0, 'Pune', 'Maharashtra', 'Aditya Roy'),

-- Sports (26-30)
(26, 'DSC Complete Premium Cricket Kit', 'Full kit including English Willow bat, leg guards, batting gloves, helmet, elbow guard, and kitbag. Perfect for weekend matches.', 200.0, 'Sports', '/images/items/cricket_kit.jpg', 1, 1, 1000.0, 2000.0, 'Mumbai', 'Maharashtra', 'Sachin Tendulkar'),
(27, 'YONEX Carbonex 8000 Set (2 Rackets)', 'Pair of Yonex rackets with 3 plastic shuttlecocks and a net. Perfect for playing in housing society compounds or local parks.', 80.0, 'Sports', '/images/items/badminton_set.jpg', 1, 1, 400.0, 800.0, 'Hyderabad', 'Telangana', 'Saina Nehwal'),
(28, 'Nivia Storm Football (Size 5)', 'Sturdy rubber football with air pump and needle. Excellent grip and durability for playing on turf or ground.', 30.0, 'Sports', '/images/items/football.jpg', 1, 2, 150.0, 300.0, 'Bengaluru', 'Karnataka', 'Sunil Chhetri'),
(29, 'Rubx Chrome Dumbbells (15kg Pair)', 'Set of two 15 kg chrome dumbbells. Non-slip grip, hexagonal design prevents rolling. Perfect for setting up a short-term home gym.', 100.0, 'Sports', '/images/items/gym_dumbbells.jpg', 1, 2, 500.0, 1200.0, 'Mumbai', 'Maharashtra', 'Hrithik Roshan'),
(30, 'Boldfit Yoga Mat (6mm TPE)', 'Eco-friendly, slip-resistant TPE yoga mat with carrying strap. Cushions joints during workouts, yoga, or pilates. Sanitized after every use.', 30.0, 'Sports', '/images/items/yoga_mat.jpg', 1, 1, 150.0, 350.0, 'Pune', 'Maharashtra', 'Shilpa Shetty'),

-- Books (31-35)
(31, 'Mechanical Engineering Sem-5 Textbook Set', 'Set of 5 core textbooks for 5th Semester Mechanical Engineering (Thermal, Fluid, Machine Design, etc.). Clean pages, no highlighting.', 50.0, 'Books', '/images/items/engineering_books.jpg', 1, 1, 250.0, 500.0, 'Chennai', 'Tamil Nadu', 'Rahul Gupta'),
(32, 'M. Laxmikanth Indian Polity (Latest Edition)', 'The bible for Indian Polity by M. Laxmikanth. Extremely useful for UPSC Civil Services preparation. Very neat, clean, and latest edition.', 40.0, 'Books', '/images/items/upsc_books.jpg', 1, 1, 200.0, 400.0, 'Delhi', 'Delhi', 'IAS Aspirant'),
(33, 'NCERT Class 10 Complete Textbook Set', 'Set of Class 10 NCERT books including Maths, Science, Social Science, and English. Perfect for CBSE board exam prep.', 30.0, 'Books', '/images/items/ncert_sets.jpg', 1, 2, 150.0, 300.0, 'Madurai', 'Tamil Nadu', 'Priya Sharma'),
(34, 'RS Aggarwal Quantitative Aptitude', 'Quantitative Aptitude and Logical Reasoning by RS Aggarwal. Essential for bank exams, placements, and MBA prep. Kept in good condition.', 25.0, 'Books', '/images/items/aptitude_books.jpg', 1, 2, 120.0, 250.0, 'Hyderabad', 'Telangana', 'Aakash Singh'),
(35, 'Best of Chetan Bhagat Novel Set (5 Books)', 'Paperback editions of 3 Mistakes of My Life, 2 States, Half Girlfriend, Five Point Someone, and One Indian Girl. Good light read.', 20.0, 'Books', '/images/items/fiction_books.jpg', 1, 1, 100.0, 200.0, 'Coimbatore', 'Tamil Nadu', 'Rinki Sen'),

-- Camping Gear (36-40)
(36, 'Quechua Arpenaz 2-Person Camping Tent', 'Waterproof, wind-resistant 2-person dome tent from Decathlon. Easy setup in under 5 minutes. Includes pegs and carrying bag.', 150.0, 'Camping Gear', '/images/items/tent.jpg', 1, 1, 750.0, 1500.0, 'Kochi', 'Kerala', 'Trekker Anand'),
(37, 'Coleman Mummy Sleeping Bag (-5°C)', 'Insulated, ultra-warm mummy sleeping bag suitable for high altitude camping. Comfort range up to -5 degrees. Freshly dry-cleaned.', 80.0, 'Camping Gear', '/images/items/sleeping_bag.jpg', 1, 1, 400.0, 1000.0, 'Delhi', 'Delhi', 'Himalayan Nomad'),
(38, 'Portable Butane Camping Gas Stove', 'Compact, windproof butane gas stove with automatic ignition. Perfect for outdoor cooking during treks and car camping. Gas canister not included.', 70.0, 'Camping Gear', '/images/items/camping_stove.jpg', 1, 2, 350.0, 800.0, 'Pune', 'Maharashtra', 'Camp Chef'),
(39, 'Decathlon Forclaz Trekking Pole (Pair)', 'Adjustable anti-shock hiking poles. Reduces impact on knees during descents. Ergonomic foam grip. Essential for steep treks.', 40.0, 'Camping Gear', '/images/items/trekking_pole.jpg', 1, 2, 200.0, 500.0, 'Coimbatore', 'Tamil Nadu', 'Mountain Goat'),
(40, 'Quechua Rechargeable Camping Lantern', 'Rechargeable LED camping lantern with multiple brightness modes and USB output to charge phones. Up to 10 hours runtime on low mode.', 30.0, 'Camping Gear', '/images/items/camping_lantern.jpg', 1, 1, 150.0, 400.0, 'Mysuru', 'Karnataka', 'Forest Camp'),

-- Home Appliances (41-45)
(41, 'Philips EasySpeed 1000W Steam Iron', 'Steam iron with non-stick soleplate and continuous steam output. Easily removes stubborn creases from cotton and linen fabrics.', 40.0, 'Home Appliances', '/images/items/iron_box.jpg', 1, 1, 200.0, 400.0, 'Chennai', 'Tamil Nadu', 'Lalitha Prasad'),
(42, 'Eureka Forbes Trendy Zip Vacuum', 'Compact and powerful 1000W canister vacuum cleaner with dust bag full indicator and multiple attachments for sofas, carpets, and corners.', 120.0, 'Home Appliances', '/images/items/vacuum_cleaner.jpg', 1, 1, 600.0, 1500.0, 'Mumbai', 'Maharashtra', 'Sanjay Dutt'),
(43, 'Kent Ultra Storage UV Water Purifier', 'Active UV water purifier with storage tank. Ideal for houses with tap water supply. Ready to connect and plug in.', 150.0, 'Home Appliances', '/images/items/water_purifier.jpg', 1, 2, 750.0, 2000.0, 'Madurai', 'Tamil Nadu', 'Harish Kumar'),
(44, 'Usha Janome Dream Stitch Sewing Machine', 'Compact automatic sewing machine with 7 built-in stitches and 14 stitch functions. Perfect for alterations, quilting, and crafts.', 150.0, 'Home Appliances', '/images/items/sewing_machine.jpg', 1, 2, 700.0, 2500.0, 'Ahmedabad', 'Gujarat', 'Geeta Ben'),
(45, 'Usha Maxx Air 400mm Pedestal Fan', 'High-speed pedestal fan with auto-oscillation and height adjustment. Perfect to beat the summer heat or for outdoor gatherings.', 50.0, 'Home Appliances', '/images/items/pedestal_fan.jpg', 1, 1, 250.0, 600.0, 'Hyderabad', 'Telangana', 'Vinay Kumar'),

-- Event Items (46-50)
(46, 'Sony MHC-V13 High-Power Audio System', 'All-in-one party speaker with Bluetooth, USB, and CD. Features party lights, mic input for karaoke, and massive bass. Ideal for house parties.', 400.0, 'Event Items', '/images/items/party_speakers.jpg', 1, 1, 200.0, 4000.0, 'Pune', 'Maharashtra', 'DJ Karan'),
(47, 'LED Fairy String Lights (Set of 10)', 'Warm white fairy lights, each 10 meters long. Waterproof copper wire, great for Diwali, Christmas, birthdays, or balcony decorations.', 50.0, 'Event Items', '/images/items/decorative_lights.jpg', 1, 1, 200.0, 300.0, 'Mumbai', 'Maharashtra', 'Rishi Kapoor'),
(48, 'Event Pop-up Gazebo Tent (10x10 ft)', 'Waterproof pop-up canopy tent. Erects in minutes without tools. Excellent shelter for birthday parties, exhibition stalls, or garden events.', 300.0, 'Event Items', '/images/items/foldable_canopy.jpg', 1, 2, 1500.0, 3000.0, 'Delhi', 'Delhi', 'Alok Nath'),
(49, 'Stainless Steel Buffet Server (Set of 3)', 'Elegant stainless steel chafing dishes with fuel holders. Keeps food warm during family functions or home parties. Easy to clean.', 150.0, 'Event Items', '/images/items/chafing_dish.jpg', 1, 2, 700.0, 1500.0, 'Kochi', 'Kerala', 'Caterer Mohan'),
(50, 'Singing Machine Wireless Dual Mic System', 'Dual wireless microphone set with receiver. Plugs into any speaker or amplifier. Perfect for home karaoke, family singing, or speeches.', 100.0, 'Event Items', '/images/items/karaoke_mic.jpg', 1, 1, 500.0, 1000.0, 'Bengaluru', 'Karnataka', 'Sonu Nigam');
